### ISSUE TITLE
dll not found

### ISSUE THREAD

**Issue by shoukailiang** [alvisisme/how-to-use-sqlite3-on-hololens2#1]
![image](https://user-images.githubusercontent.com/24668909/194309005-bea9b9f3-5648-4585-9f52-30013c55c0fb.png)

**Comment by alvisisme** [comment]
dll 是由工程内部的 [sqlite3.c](https://github.com/alvisisme/how-to-use-sqlite3-on-hololens2/blob/master/Assets/Scripts/sqlite3.c) 源码自动编译出来的，需要查看开发环境的版本有没有差异，确认下unity 有没有自动编译 C 源码。

**Comment by shoukailiang** [comment]
> dll 是由工程内部的 [sqlite3.c](https://github.com/alvisisme/how-to-use-sqlite3-on-hololens2/blob/master/Assets/Scripts/sqlite3.c) 源码自动编译出来的，需要查看开发环境的版本有没有差异，确认下unity 有没有自动编译 C 源码。

ok,我再看看。我直接clone了你的项目。发现他报这个错

**Comment by alvisisme** [comment]
先在真机上运行看看是否可以，editor 环境下有人反馈可能会失败，原因不明。
也可以按照 README 的流程自己重新建一个工程，主要就是 Scripts 下面放一个 sqlite C 源码和对应的 C# 接口，C源码编译为 dll 理论上在 Unity 上是自动的，我这里直接克隆导入unity编译下就出来了。
