### ISSUE TITLE
请问如何使用？

### ISSUE THREAD

**Issue by OopsAngela** [alvisisme/how-to-use-sqlite3-on-hololens2#2]
你好，我将工程用UNITY打开，并打包到Hololens 2，并没有输出数据库内容。用编辑器运行会报错：
DllNotFoundException: sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null)
SQLite.SQLiteConnection..ctor (SQLite.SQLiteConnectionString connectionString) (at Assets/Scripts/SQLite.cs:293)
我是漏掉什么步骤或者必要操作吗？

**Comment by alvisisme** [comment]
直接导入工程到对应 Unity 版本就可以，注意查看下软件版本和 readme 上是否一致。
编辑器模式下 sqlite 源码生成 dll 不是很稳定，遇到过几次运行报错，重启几次又可以了，原因不明。编辑器模式下还可以直接从 sqlite 官方下载 windows 的 dll 二进制使用，注意将对应 dll 标记为 windows 平台可用。

**Comment by OopsAngela** [comment]
> 直接导入工程到对应 Unity 版本就可以，注意查看下软件版本和 readme 上是否一致。 编辑器模式下 sqlite 源码生成 dll 不是很稳定，遇到过几次运行报错，重启几次又可以了，原因不明。编辑器模式下还可以直接从 sqlite 官方下载 windows 的 dll 二进制使用，注意将对应 dll 标记为 windows 平台可用。

谢谢回复，我再次尝试下。
